image = "/users/ealnuaim/.local/enroot/testcase3-clariden.sqsh"
workdir = "/users/ealnuaim"
writable = true

mounts = [
  "/users/ealnuaim:/users/ealnuaim"
]
[annotations]
com.hooks.cxi.enabled = "true"
com.hooks.nvidia_cuda_mps.enabled = "true"

