image = "/iopsstor/scratch/cscs/mcopik/xaas-containers-artifact/microbenchmarks/alps-distributed-containers/containers/osu-ompi.sqsh"

[env]
#FI_LOG_LEVEL="debug"
#UCX_LOG_LEVEL="trace"

[annotations]
com.hooks.cxi.enabled="false"
