image = "ealnuaimi/testcase3-clariden:latest"
workdir = "/iopsstor/scratch/cscs/mcopik"
writable = true

mounts = [
  "/iopsstor/scratch/cscs/mcopik:/iopsstor/scratch/cscs/mcopik"
]
[annotations]
com.hooks.cxi.enabled = "true"
#com.hooks.nvidia_cuda_mps.enabled = "true"
#com.hooks.aws_ofi_nccl.enabled = "true"
#com.hooks.aws_ofi_nccl.variant = "cuda12"
